
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xsvm_speech_30.h"

/*
* The configuration table for devices
*/

XSvm_speech_30_Config XSvm_speech_30_ConfigTable[XPAR_XSVM_SPEECH_30_NUM_INSTANCES] =
{
	{
		XPAR_SVM_SPEECH_30_0_DEVICE_ID,
		XPAR_SVM_SPEECH_30_0_S_AXI_CONTROL_BASEADDR,
		XPAR_SVM_SPEECH_30_0_S_AXI_INPUTPART1_BASEADDR,
		XPAR_SVM_SPEECH_30_0_S_AXI_INPUTPART2_BASEADDR,
		XPAR_SVM_SPEECH_30_0_S_AXI_INPUTPART3_BASEADDR,
		XPAR_SVM_SPEECH_30_0_S_AXI_INPUTPART4_BASEADDR
	}
};


